name:                           Coverage

on:                             [push]
jobs:
  test:
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined
    if:                         ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2
      - name: Cache target
        uses: actions/cache@v2
        env:
          cache-name: cache-default-target-and-lockfile
        with:
          path: |
            target
            Cargo.lock
            ~/.rustup
          key: ${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
      - name:                   Build HTTP server binary
        run: cargo +nightly build --all-features
      - name:                   Generate code coverage
        run: |
          RUST_MIN_STACK=8388608 cargo +nightly tarpaulin --skip-clean --all-features --workspace --timeout 600 --out Xml -- --nocapture
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
          token:                ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error:     true
