name: Dependabot-Alerts
on:
  pull_request:
    branches:
      - 'dependabot/**'
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04658EJ9QS'
          slack-message: "New Dependabot PR: ${{ job.status }} - ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
