on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --features "bin"
      - run: cargo test
      - run: cargo clippy -- -Dwarnings
      - run: sed -i 's/tandem_garble_interop/#tandem_garble_interop/' tandem/Cargo.toml
      - run: cargo publish -p tandem --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: sleep 60 && cargo publish -p tandem_garble_interop --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: sleep 60 && cargo publish -p tandem_http_client --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish -p tandem_http_server --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
